--- 
abstract: Database source for Algorithm::Dependency
author: Adam Kennedy <cpan@ali.as>
build_requires: 
  File::Spec: 0.80
  File::Temp: 0
  Test::More: 0.42
distribution_type: module
generated_by: Module::Install version 0.65
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Algorithm-Dependency-Source-DBI
no_index: 
  directory: 
    - inc
    - t
requires: 
  Algorithm::Dependency: 1.102
  DBI: 0
  Params::Util: 0.23
  perl: 5.005
version: 0.03
